### PR TITLE
Added new property 'spacerStyle'

### PR DESCRIPTION
**Pull request by artsur**
If some additional styles required for spacers. For example: in case to use this library for optimize list with css grid, it is required to provide css properies gridColumnStart and gridColumnEnd. Moreover, this props may changes dynamically.

### CODE REVIEW

**Comment by oleggrishechkin** [comment]
Hi, @artsur, thank you for your PR. Everythink is good. 

I thought about spacer customization recently. Spacer style is not a common solution. What if we want to apply different styles to our spacers (top or bottom)? I think we can extend `spacerElement` prop  to `spacerElement: ({ ref, style, startIndex, endIndex, cache, type }) => ReactNode` because it allow us to use any component or tag for spacer and use some data to render like indexes to render, type of spacer (top or bottom). Yes, this api is harder than just a style object, but it cover more use cases

**Comment by artsur** [comment]
Maybe you're right. I just tried to implement react-viewport-list to optimize table with css grid. Additional styles in this case are enough. Perhaps for some cases your solution of spacers as React Node would be better. If you have your own solution, just reject the pull request.
In addition, I would like to draw your attention to the possibility of rendering tables based on css grid.
At the moment I have not been able to implement it correctly. For each row in the table, I use a wrapper with display: contents property. The height of such elements is naturally equal to zero. I use the itemMinSize parameter, but the spacers are not always calculated correctly. I will think about this too.

**Comment by oleggrishechkin** [comment]
> Maybe you're right. I just tried to implement react-viewport-list to optimize table with css grid. Additional styles in this case are enough. Perhaps for some cases your solution of spacers as React Node would be better. If you have your own solution, just reject the pull request. In addition, I would like to draw your attention to the possibility of rendering tables based on css grid. At the moment I have not been able to implement it correctly. For each row in the table, I use a wrapper with display: contents property. The height of such elements is naturally equal to zero. I use the itemMinSize parameter, but the spacers are not always calculated correctly. I will think about this too.

Do you use tables? (I mean`<table>`) Or just <div> this css grid layout?

**Comment by oleggrishechkin** [comment]
@artsur I merged this PR, thank you for your first conribution.

**Comment by artsur** [comment]
> @artsur I merged this PR, thank you for your first conribution.

Thank you for useful component.

> Do you use tables? (I mean<table>) Or just <div> with css grid layout?

It doesn't matter. It can be used with both native html tables and tables built by <div>. The main thing in both cases: css style for root element should be 'display: grid'. 
Each <tr> in case of using <table> should have style 'display: contents'. The prop spacerElement = 'tr' in this case.
In case of using <div>, each table row should be presented by <div> with style 'display: contents'. And spacerElement can be 'aside' or 'section' for example.

In addition, in the case of using grid, you need to define styles:
```
spacerStyle={{
  gridColumnStart: 1,
  gridColumnEnd: columns.length + 1,
  display: 'block',
}}
```

However, since an element with style display : contents has no height, you must specify itemMinSize. And sometimes it doesn't work correctly. I'm trying to figure out why. I think display:contents is the problem.

PS. With flexbox it works perfect!

**Pull request merged**
